### ISSUE TITLE
Create figure.yml file

### ISSUE THREAD

**Issue by geealbers** [thegetty/rococo#2]
We'll need to convert the captions Word doc to markdown (which will preserve italics), and then structure it as YAML in our standard `figures.yml` format. There's a `figures.yml` file in there now which you can trash. But as an example of how a properly formatted file will ultimately look here are the first two entries from that:

```yaml
figure_list:

  - id: "fig-3-1"
    src: "figuress/fig-3-1.jpg"
    label: "Fig. 3-1"
    caption: "Black lacquer cartonnier, Bernard II van Risenburgh, Main View, 3/4 right front"
 
 - id: "fig-3-2"
    src: "figuress/fig-3-2.jpg"
    label: "Fig. 3.2"
    caption: "Black lacquer cartonnier, Bernard II van Risenburgh, front, 83.DA.280"
```

In the caption doc, there are also Catalogue entry images in bold (1 per entry). These should be included in the `figures.yml` file as well. And would look something like:

```
  - id: "cat-3"
    src: "figuress/cat-3.jpg"
    label: "Cat. 3"
    caption: "Main view: 3/4 right front, with side door open"
```

**Downloads:**

For any image that's a Getty image, we want to enable downloading. For this we should add `download: true` to all the relevant figure yaml entries. This would be easy to do to ALL the entries at the end with a global find and replace, and then you'd just need to go back and manually turn any to `false`. This might be easier than manually adding them in because most images are Getty images.

**Notes:** 

- The standard naming convention for IDs and the filename will lowercase "fig" with dashes separating the numbers. or "cat" in the place of "fig" for catalogue entry images.
- Surround values with double straight quote to prevent validation issues, with the exception of `download: true/false` which should be unquoted.
- Put a line space between figure entries to help with legibility in the file
- For the labels, please confirm with @rabarth1 and Tevvy how they would like them to appear. In the captions Word doc, they are "Fig. 3-1" (abbreviated and with a dash), whereas in our latest book, Mummy Portraits, we used "Figure 3.1" (spelled out and with a period). Happy to do whatever they'd like, just want to double-check.
